#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	config_load nook
	config_get_bool enabled main enabled 1
	config_get listen main listen '0.0.0.0:8088'

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/nook -listen "$listen"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "nook"
}
